/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author USER
 */
public class Español extends javax.swing.JFrame {

    /**
     * Creates new form Español
     */
    public Español() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonTrans();
    }
    public void buttonTrans(){
         b_cer.setOpaque(false); b_cer.setContentAreaFilled(false); b_cer.setBorderPainted(false);
        b_min.setOpaque(false); b_min.setContentAreaFilled(false); b_min.setBorderPainted(false);
         b_teclado.setOpaque(false); b_teclado.setContentAreaFilled(false); b_teclado.setBorderPainted(false);
          b_teclado1.setOpaque(false); b_teclado1.setContentAreaFilled(false); b_teclado1.setBorderPainted(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_cer = new javax.swing.JButton();
        b_min = new javax.swing.JButton();
        b_teclado = new javax.swing.JButton();
        b_teclado1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_cer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        b_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerActionPerformed(evt);
            }
        });
        getContentPane().add(b_cer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 40, -1));

        b_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        b_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_minActionPerformed(evt);
            }
        });
        getContentPane().add(b_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 40, -1));

        b_teclado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_teclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/medicina.png"))); // NOI18N
        b_teclado.setText("Aprenda a escribir en el teclado");
        b_teclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tecladoActionPerformed(evt);
            }
        });
        getContentPane().add(b_teclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 380, -1));

        b_teclado1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_teclado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/medicina.png"))); // NOI18N
        b_teclado1.setText("Aprenda a escribir en el teclado 2");
        b_teclado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_teclado1ActionPerformed(evt);
            }
        });
        getContentPane().add(b_teclado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 380, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/letras.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 580));

        jButton1.setText("Gramatica");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jButton2.setText("Reglas de ortografía");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jButton3.setText("OCHO LECCIONES DE ORTOGRAFIA ");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cerActionPerformed

    private void b_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_minActionPerformed
        setExtendedState(Español.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_b_minActionPerformed

    private void b_tecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tecladoActionPerformed
                    try
{
   /* directorio/ejecutable es el path del ejecutable y un nombre */
   Process p = Runtime.getRuntime().exec ("Leer/mecanet.exe");
}
catch (Exception e)
{
   /* Se lanza una excepción si no se encuentra en ejecutable o el fichero no es ejecutable. */
}
    }//GEN-LAST:event_b_tecladoActionPerformed

    private void b_teclado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_teclado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_teclado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Español.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Español.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Español.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Español.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Español().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cer;
    private javax.swing.JButton b_min;
    private javax.swing.JButton b_teclado;
    private javax.swing.JButton b_teclado1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
