/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import com.sun.awt.AWTUtilities;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {
private static Scanner sc;
private static int intentos;
private static String user, pwd, email;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        botonsinF();
        this.setLocationRelativeTo(this);
      //  AWTUtilities.setWindowOpaque(this, false);
        
      //  txt_pwd.setVisible(true);
      txt_pwd.setText(txt_pwdOcul.getText());
      txt_pwdOcul.setText(txt_pwd.getText());
    }
    
    public void botonsinF(){
        b_olvido.setOpaque(false);
        b_olvido.setBorderPainted(false);
        b_olvido.setContentAreaFilled(false);
        B_salir.setOpaque(false);
        B_salir.setBorderPainted(false);
        B_salir.setContentAreaFilled(false);
        B_minimizar.setOpaque(false);
        B_minimizar.setBorderPainted(false);
        B_minimizar.setContentAreaFilled(false);
        
        
    }

//    public static void setIntentos(int intentos) {
//        Login.intentos = intentos;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usu = new javax.swing.JTextField();
        txt_pwdOcul = new javax.swing.JLabel();
        txt_pwd = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JCheckBox();
        b_registrarse = new javax.swing.JButton();
        b_Inicio = new javax.swing.JButton();
        b_olvido = new javax.swing.JButton();
        B_minimizar = new javax.swing.JButton();
        B_salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usu.setBackground(new java.awt.Color(214, 217, 223));
        txt_usu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_usu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txt_usu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuKeyTyped(evt);
            }
        });
        getContentPane().add(txt_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 180, 20));

        txt_pwdOcul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_pwdOcul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        getContentPane().add(txt_pwdOcul, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 180, 20));

        txt_pwd.setBackground(new java.awt.Color(214, 217, 223));
        txt_pwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_pwd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        txt_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwdActionPerformed(evt);
            }
        });
        txt_pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pwdKeyTyped(evt);
            }
        });
        getContentPane().add(txt_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 180, 20));

        mostrar.setText("Mostrar ");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        b_registrarse.setBackground(new java.awt.Color(0, 0, 255));
        b_registrarse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        b_registrarse.setText("Registrarse");
        b_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_registrarseActionPerformed(evt);
            }
        });
        getContentPane().add(b_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 120, 30));

        b_Inicio.setBackground(new java.awt.Color(0, 153, 0));
        b_Inicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        b_Inicio.setText("Iniciar Sección");
        b_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_InicioActionPerformed(evt);
            }
        });
        getContentPane().add(b_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 120, 30));

        b_olvido.setBackground(new java.awt.Color(255, 255, 255));
        b_olvido.setFont(new java.awt.Font("Sitka Subheading", 3, 10)); // NOI18N
        b_olvido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/olvido.png"))); // NOI18N
        b_olvido.setBorder(null);
        b_olvido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_olvidoActionPerformed(evt);
            }
        });
        getContentPane().add(b_olvido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 50, 40));

        B_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        B_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(B_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 40, 40));

        B_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        B_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_salirActionPerformed(evt);
            }
        });
        getContentPane().add(B_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TTT.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 220, 220));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel3.setText("¿Olvido su password?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/grupo-de-usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 70, 90));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Usuario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 180, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Contraseña");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/candado.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 180, 10));

        fondo1.setBackground(new java.awt.Color(255, 255, 255));
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blan.png"))); // NOI18N
        fondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 310, 370));

        fondo2.setBackground(new java.awt.Color(0, 0, 153));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris.png"))); // NOI18N
        fondo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 380, 370));

        fondo.setBackground(new java.awt.Color(0, 0, 153));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/106.jpg"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_B_salirActionPerformed

    private void B_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_minimizarActionPerformed
      setExtendedState(Login.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_B_minimizarActionPerformed

    
    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed

        if(mostrar.isSelected()){

                        txt_pwd.setVisible(false);
            txt_pwdOcul.setVisible(true);
            txt_pwdOcul.setText(txt_pwd.getText());
            
        }else{
            txt_pwd.setVisible(true);
            txt_pwd.setText(txt_pwdOcul.getText());
            txt_pwdOcul.setVisible(false);
        }
        
    }//GEN-LAST:event_mostrarActionPerformed

    private void b_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_registrarseActionPerformed
       Registrarse  R = new Registrarse();
       R.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_b_registrarseActionPerformed

    private void b_olvidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_olvidoActionPerformed
       Olvido Ol = new Olvido();
       Ol.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_b_olvidoActionPerformed

    private void b_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_InicioActionPerformed
        FileReader fr = null;
        try {
        int NLinea = 0; int i =0;
        String[] usuarios = null; String linea;
        sc = new Scanner(new File("Datos.txt"));
        File  f = new File("Datos.txt");
        fr =  new FileReader(f);
        BufferedReader br = new  BufferedReader(fr);
            try {
                while((linea = br.readLine()) != null){
                    NLinea ++;
                    
                 }  
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        usuarios = new String[NLinea];
        while(sc.hasNextLine()){
            usuarios[i++] = sc.nextLine();
            
        }
        intentos ++;
        user =  txt_usu.getText();
        pwd = txt_pwd.getText();
        Seguridad s = new Seguridad();
        s.ValidarUsuario(usuarios, user, pwd, intentos);
        txt_usu.setText("");
        txt_pwd.setText("");
        txt_pwdOcul.setText("");
        
        

    } catch (FileNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

    }

//        Menu M = new Menu();
//        M.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_b_InicioActionPerformed

    private void txt_usuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuKeyTyped
               char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_usuKeyTyped

    private void txt_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwdActionPerformed

    private void txt_pwdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwdKeyTyped
        char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_pwdKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_minimizar;
    private javax.swing.JButton B_salir;
    private javax.swing.JButton b_Inicio;
    private javax.swing.JButton b_olvido;
    private javax.swing.JButton b_registrarse;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JPasswordField txt_pwd;
    private javax.swing.JLabel txt_pwdOcul;
    private javax.swing.JTextField txt_usu;
    // End of variables declaration//GEN-END:variables
}
