/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Matematicas extends javax.swing.JFrame {

    /**
     * Creates new form Matematicas
     */
    public Matematicas() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonTrans();
        butonInvi();
    }
    public void butonInvi(){
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(false); txt_14.setVisible(false);
        b_1.setVisible(false); b_2.setVisible(false);
        b_3.setVisible(false); b_4.setVisible(false);
        b_5.setVisible(false); b_6.setVisible(false);
        b_7.setVisible(false); b_8.setVisible(false);
        b_9.setVisible(false); b_10.setVisible(false);
        b_11.setVisible(false); b_12.setVisible(false);
        b_13.setVisible(false); b_14.setVisible(false);
        jj1.setVisible(false);
    }
    public void buttonTrans(){
        b_cerr.setOpaque(false); b_cerr.setContentAreaFilled(false); b_cerr.setBorderPainted(false);
        b_min.setOpaque(false); b_min.setContentAreaFilled(false); b_min.setBorderPainted(false);
        b_pi.setBorderPainted(false); b_pi.setContentAreaFilled(false); b_pi.setOpaque(false);
        jButton1.setOpaque(false); jButton1.setBorderPainted(false); jButton1.setContentAreaFilled(false);
        jButton2.setOpaque(false); jButton2.setBorderPainted(false); jButton2.setContentAreaFilled(false);
        jButton3.setOpaque(false); jButton3.setBorderPainted(false); jButton3.setContentAreaFilled(false);
        jButton4.setOpaque(false); jButton4.setBorderPainted(false); jButton4.setContentAreaFilled(false);
        jButton5.setOpaque(false); jButton5.setBorderPainted(false); jButton5.setContentAreaFilled(false);
        
    }
    
    public void borr(){
        txt_1.setText(""); txt_2.setText(""); txt_3.setText("");
        txt_4.setText(""); txt_5.setText(""); txt_6.setText("");
        txt_7.setText(""); txt_8.setText(""); txt_9.setText("");
        txt_10.setText(""); txt_11.setText(""); txt_12.setText("");
        txt_13.setText(""); txt_14.setText(""); 
    }
    
   
        double lado, base, altura, resultado, perimetro, apotema, radioMa, radioMe, diametro,
                angulo, baseMa, baseMe, diagMa, area, diagMe = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jj1 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        A_1 = new javax.swing.JButton();
        A_2 = new javax.swing.JButton();
        A_3 = new javax.swing.JButton();
        A_4 = new javax.swing.JButton();
        A_5 = new javax.swing.JButton();
        A_6 = new javax.swing.JButton();
        A_7 = new javax.swing.JButton();
        A_8 = new javax.swing.JButton();
        A_9 = new javax.swing.JButton();
        A_10 = new javax.swing.JButton();
        A_11 = new javax.swing.JButton();
        A_12 = new javax.swing.JButton();
        A_13 = new javax.swing.JButton();
        A_14 = new javax.swing.JButton();
        lb_1 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        lb_2 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JTextField();
        lb_3 = new javax.swing.JLabel();
        txt_3 = new javax.swing.JTextField();
        lb_4 = new javax.swing.JLabel();
        txt_4 = new javax.swing.JTextField();
        lb_5 = new javax.swing.JLabel();
        txt_5 = new javax.swing.JTextField();
        lb_6 = new javax.swing.JLabel();
        txt_6 = new javax.swing.JTextField();
        lb_7 = new javax.swing.JLabel();
        txt_7 = new javax.swing.JTextField();
        lb_8 = new javax.swing.JLabel();
        txt_8 = new javax.swing.JTextField();
        lb_9 = new javax.swing.JLabel();
        txt_9 = new javax.swing.JTextField();
        lb_10 = new javax.swing.JLabel();
        txt_10 = new javax.swing.JTextField();
        lb_11 = new javax.swing.JLabel();
        txt_11 = new javax.swing.JTextField();
        lb_12 = new javax.swing.JLabel();
        txt_12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lb_13 = new javax.swing.JLabel();
        txt_13 = new javax.swing.JTextField();
        lb_14 = new javax.swing.JLabel();
        txt_14 = new javax.swing.JTextField();
        Resultado = new javax.swing.JLabel();
        b_16 = new javax.swing.JButton();
        b_4 = new javax.swing.JButton();
        b_5 = new javax.swing.JButton();
        b_6 = new javax.swing.JButton();
        b_7 = new javax.swing.JButton();
        b_8 = new javax.swing.JButton();
        b_9 = new javax.swing.JButton();
        b_10 = new javax.swing.JButton();
        b_11 = new javax.swing.JButton();
        b_12 = new javax.swing.JButton();
        b_13 = new javax.swing.JButton();
        b_14 = new javax.swing.JButton();
        b_1 = new javax.swing.JButton();
        b_2 = new javax.swing.JButton();
        b_3 = new javax.swing.JButton();
        b_15 = new javax.swing.JButton();
        b_cerr2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        b_min = new javax.swing.JButton();
        b_cerr = new javax.swing.JButton();
        b_pi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jj1.setVisible(true);
        jj1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("AREAS");
        jj1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("VOLUMENES");
        jj1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        A_1.setText("Cuadrado");
        A_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_1ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        A_2.setText("Rectángulo");
        A_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_2ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        A_3.setText("Paralelogramo");
        A_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_3ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        A_4.setText("Triángulo");
        A_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_4ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        A_5.setText("Trapecio");
        A_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_5ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        A_6.setText("Rombo");
        A_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_6ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        A_7.setText("Plogono Regular");
        A_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_7ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        A_8.setText("Corona Circular");
        A_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_8ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        A_9.setText("Sector Circular");
        A_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_9ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        A_10.setText("Prisma n Números de caras");
        A_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_10ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        A_11.setText("Cubo");
        A_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_11ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 80, -1));

        A_12.setText("Esfera");
        A_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_12ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 90, -1));

        A_13.setText("Cilindro");
        A_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_13ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 80, -1));

        A_14.setText("Cono");
        A_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_14ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(A_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 190, 90, -1));

        lb_1.setText("Ingrese el lado:");
        jj1.getContentPane().add(lb_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));
        jj1.getContentPane().add(txt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, -1));

        lb_2.setText("Ingrese la base:");
        jj1.getContentPane().add(lb_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 90, 10));
        jj1.getContentPane().add(txt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 80, -1));

        lb_3.setText("Ingrese la altura");
        jj1.getContentPane().add(lb_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));
        jj1.getContentPane().add(txt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 80, -1));

        lb_4.setText("Ingrese el perimetro:");
        jj1.getContentPane().add(lb_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        jj1.getContentPane().add(txt_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, -1));

        lb_5.setText("Ingrese la apotema:");
        jj1.getContentPane().add(lb_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));
        jj1.getContentPane().add(txt_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 80, -1));

        lb_6.setText("Ingrese el radio menor:");
        jj1.getContentPane().add(lb_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        jj1.getContentPane().add(txt_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, -1));

        lb_7.setText("Ingrese el radio mayor:");
        jj1.getContentPane().add(lb_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));
        jj1.getContentPane().add(txt_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 80, -1));

        lb_8.setText("Ingrese el Diametro:");
        jj1.getContentPane().add(lb_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));
        jj1.getContentPane().add(txt_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 80, -1));

        lb_9.setText("Ingrese la diagonal mayor:");
        jj1.getContentPane().add(lb_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));
        jj1.getContentPane().add(txt_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, -1));

        lb_10.setText("Ingrese la diagonal menor:");
        jj1.getContentPane().add(lb_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));
        jj1.getContentPane().add(txt_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 80, -1));

        lb_11.setText("Ingrese la base mayor:");
        jj1.getContentPane().add(lb_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        jj1.getContentPane().add(txt_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, -1));

        lb_12.setText("Ingrese la base menor:");
        jj1.getContentPane().add(lb_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));
        jj1.getContentPane().add(txt_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("BIENVENIDO");
        jj1.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        lb_13.setText("Ingrese el Angulo:");
        jj1.getContentPane().add(lb_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        txt_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_13ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(txt_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 80, -1));

        lb_14.setText("Ingrese el Radio");
        jj1.getContentPane().add(lb_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));
        jj1.getContentPane().add(txt_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 80, -1));

        Resultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jj1.getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 260, 50));

        b_16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/borrador_1.png"))); // NOI18N
        b_16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_16ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 100, 70));

        b_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_5ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_6ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_7ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_8ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_9ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_10ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_11ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_12ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_13ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_14ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_1ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_2ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        b_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_3ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/pizarra.png"))); // NOI18N
        b_15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.red, java.awt.Color.red, null, java.awt.Color.red));
        jj1.getContentPane().add(b_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 100, 70));

        b_cerr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        b_cerr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerr2ActionPerformed(evt);
            }
        });
        jj1.getContentPane().add(b_cerr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 40, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f_verde.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jj1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 520));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        b_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_minActionPerformed(evt);
            }
        });
        getContentPane().add(b_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 40, -1));

        b_cerr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        b_cerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerrActionPerformed(evt);
            }
        });
        getContentPane().add(b_cerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 40, -1));

        b_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_piActionPerformed(evt);
            }
        });
        getContentPane().add(b_pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 190, 180));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Calcular Areas y Volumenes ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 310, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 0));
        jButton2.setText("Razonamiento Matemático 2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 310, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 0));
        jButton3.setText("Razonamiento Matemático 3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 310, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 153, 0));
        jButton4.setText("Razonamiento Matemático 1");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 310, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 153, 0));
        jButton5.setText("Ejercicios matemáticos en Google...");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 380, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pi.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerrActionPerformed
    this.setVisible(false);
    }//GEN-LAST:event_b_cerrActionPerformed

    private void b_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_minActionPerformed
     setExtendedState(Matematicas.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_b_minActionPerformed

    private void A_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_1ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el area de un cuadrado es : \n" + 
                       "A = lado * lado");
        lb_1.setVisible(true); txt_1.setVisible(true);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(false); txt_14.setVisible(false);
        b_1.setVisible(true);
    }//GEN-LAST:event_A_1ActionPerformed

    private void A_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_2ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el area de un rectangulo es : \n" + 
                       "A = base * lado");
        lb_1.setVisible(true); txt_1.setVisible(true);
        lb_2.setVisible(true); txt_2.setVisible(true);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(false); txt_14.setVisible(false);
        b_2.setVisible(true);
    }//GEN-LAST:event_A_2ActionPerformed

    private void A_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_3ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el area de un paralelogramo es : \n" + 
                       "A = base * altura");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(true); txt_2.setVisible(true);
        lb_3.setVisible(true); txt_3.setVisible(true);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
         lb_13.setVisible(false); txt_13.setVisible(false);
         lb_14.setVisible(false); txt_14.setVisible(false);
         b_3.setVisible(true);
    }//GEN-LAST:event_A_3ActionPerformed

    private void A_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_4ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el area de un triangulo es : \n" + 
                       "A = (base * altura) / 2");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(true); txt_2.setVisible(true);
        lb_3.setVisible(true); txt_3.setVisible(true);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_14.setVisible(false); txt_14.setVisible(false);
        b_4.setVisible(true);
    }//GEN-LAST:event_A_4ActionPerformed

    private void A_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_5ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el area de un trapecio es : \n" + 
                       "A = ((base mayor * base menor) altura) / 2");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(true); txt_3.setVisible(true);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(true); txt_11.setVisible(true);
        lb_12.setVisible(true); txt_12.setVisible(true);
         lb_13.setVisible(false); txt_13.setVisible(false);
         lb_14.setVisible(false); txt_14.setVisible(false);
         b_5.setVisible(true);
    }//GEN-LAST:event_A_5ActionPerformed

    private void A_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_6ActionPerformed
      JOptionPane.showMessageDialog(null,"Para obtener el area de un rombo es : \n" + 
        "A = (diagonal mayor * diagonal menor) / 2");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(true); txt_9.setVisible(true);
        lb_10.setVisible(true); txt_10.setVisible(true);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
         lb_13.setVisible(false); txt_13.setVisible(false);
         lb_14.setVisible(false); txt_14.setVisible(false);
         b_6.setVisible(true);
    }//GEN-LAST:event_A_6ActionPerformed

    private void A_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_7ActionPerformed
   JOptionPane.showMessageDialog(null,"Para obtener el area de un poligono regular es : \n" + 
                       "A = (perimetro * apotema) / 2");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(true); txt_4.setVisible(true);
        lb_5.setVisible(true); txt_5.setVisible(true);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
         lb_13.setVisible(false); txt_13.setVisible(false);
         lb_14.setVisible(false); txt_14.setVisible(false);
         b_7.setVisible(true);
    }//GEN-LAST:event_A_7ActionPerformed

    private void A_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_8ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el area de una Corona Circular la formula es : \n" + 
         "A = Pi * (Radio Mayor^2 - Radio Menor^2)");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(true); txt_6.setVisible(true);
        lb_7.setVisible(true); txt_7.setVisible(true);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
         lb_13.setVisible(false); txt_13.setVisible(false);
         lb_14.setVisible(false); txt_14.setVisible(false);
         b_8.setVisible(true);
    }//GEN-LAST:event_A_8ActionPerformed

    private void A_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_9ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el area de un Sector Circular la formula es : \n" + 
          "A = (Pi * Radio Mayor^2 * ángulo) / 360°");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(true); txt_7.setVisible(true);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(true); txt_13.setVisible(true);
        lb_14.setVisible(false); txt_14.setVisible(false);
        b_9.setVisible(true);
    }//GEN-LAST:event_A_9ActionPerformed

    private void A_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_10ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el volumen de un Prisma de n números de caras la formula es : \n" + 
               "V = area * altura");
        lb_1.setVisible(true); txt_1.setVisible(true);
        lb_2.setVisible(true); txt_2.setVisible(true);
        lb_3.setVisible(true); txt_3.setVisible(true);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(false); txt_14.setVisible(false);
        b_10.setVisible(true);
    }//GEN-LAST:event_A_10ActionPerformed

    private void A_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_11ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el volumen de un cubo la formula es : \n" + 
                       "V = area^3 ");
        lb_1.setVisible(true); txt_1.setVisible(true);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(false); txt_14.setVisible(false);
        b_11.setVisible(true);
    }//GEN-LAST:event_A_11ActionPerformed

    private void A_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_12ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el volumen de una esfera la formula es : \n" + 
                       "V = (4 * Pi * radio^3) / 3 ");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(false); txt_3.setVisible(false);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(true); txt_14.setVisible(true);
        b_12.setVisible(true);
    }//GEN-LAST:event_A_12ActionPerformed

    private void A_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_13ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el volumen de un cilindro la formula es : \n" + 
              "V = Pi * radio^2 * altura ");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(true); txt_3.setVisible(true);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(true); txt_14.setVisible(true);
        b_13.setVisible(true);
    }//GEN-LAST:event_A_13ActionPerformed

    private void A_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_14ActionPerformed
        JOptionPane.showMessageDialog(null,"Para obtener el volumen de un cono la formula es : \n" + 
            "V = (3.14159 * radio^2 * altura) / 3 ");
        lb_1.setVisible(false); txt_1.setVisible(false);
        lb_2.setVisible(false); txt_2.setVisible(false);
        lb_3.setVisible(true); txt_3.setVisible(true);
        lb_4.setVisible(false); txt_4.setVisible(false);
        lb_5.setVisible(false); txt_5.setVisible(false);
        lb_6.setVisible(false); txt_6.setVisible(false);
        lb_7.setVisible(false); txt_7.setVisible(false);
        lb_8.setVisible(false); txt_8.setVisible(false);
        lb_9.setVisible(false); txt_9.setVisible(false);
        lb_10.setVisible(false); txt_10.setVisible(false);
        lb_11.setVisible(false); txt_11.setVisible(false);
        lb_12.setVisible(false); txt_12.setVisible(false);
        lb_13.setVisible(false); txt_13.setVisible(false);
        lb_14.setVisible(true); txt_14.setVisible(true);
        b_14.setVisible(true);
    }//GEN-LAST:event_A_14ActionPerformed

    private void b_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_16ActionPerformed
     txt_1.setText(""); txt_2.setText(""); txt_3.setText("");
     txt_4.setText(""); txt_5.setText(""); txt_6.setText("");
     txt_7.setText(""); txt_8.setText(""); txt_9.setText("");
     txt_10.setText(""); txt_11.setText(""); txt_12.setText("");
     txt_13.setText(""); txt_14.setText(""); Resultado.setText("");
     // butonInvi();
    }//GEN-LAST:event_b_16ActionPerformed

    private void b_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_1ActionPerformed
    if (txt_1.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            lado  = Integer.parseInt(txt_1.getText());
            resultado = lado * lado;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_1ActionPerformed

    private void b_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_2ActionPerformed
     if (txt_1.getText().length() == 0 | txt_2.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            lado  = Integer.parseInt(txt_1.getText());
            base = Integer.parseInt(txt_2.getText());
            resultado = lado * base;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_2ActionPerformed

    private void b_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_3ActionPerformed
         if (txt_2.getText().length() == 0 | txt_3.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            base  = Integer.parseInt(txt_2.getText());
            altura = Integer.parseInt(txt_3.getText());
            resultado = altura * base;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_3ActionPerformed

    private void b_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4ActionPerformed
        
        if (txt_2.getText().length() == 0 | txt_3.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            altura  = Integer.parseInt(txt_3.getText());
            base = Integer.parseInt(txt_2.getText());
            resultado = (altura * base) / 2;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_4ActionPerformed

    private void b_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_5ActionPerformed
      if (txt_11.getText().length() == 0 | txt_12.getText().length() == 0 | txt_3.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            baseMa  = Integer.parseInt(txt_11.getText());
            baseMe = Integer.parseInt(txt_12.getText());
            altura = Integer.parseInt(txt_3.getText());
            resultado = (altura * (baseMa * baseMe)) / 2;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_5ActionPerformed

    private void b_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_6ActionPerformed
      if (txt_9.getText().length() == 0 | txt_10.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            diagMa  = Integer.parseInt(txt_9.getText());
            diagMe = Integer.parseInt(txt_10.getText());
            resultado = (diagMa * diagMe) / 2;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_6ActionPerformed

    private void b_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_7ActionPerformed
  if (txt_4.getText().length() == 0 | txt_5.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            perimetro  = Integer.parseInt(txt_4.getText());
            apotema = Integer.parseInt(txt_5.getText());
            resultado = (perimetro * apotema) / 2;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_7ActionPerformed

    private void b_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_8ActionPerformed
     if (txt_6.getText().length() == 0 | txt_7.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            radioMe  = Integer.parseInt(txt_6.getText());
            radioMa = Integer.parseInt(txt_7.getText());
            resultado = (3.14159 * ((radioMa*radioMa) * (radioMe*radioMe))) / 2;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_8ActionPerformed

    private void b_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_9ActionPerformed
    if (txt_13.getText().length() == 0 | txt_7.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
        //Pi * Radio Mayor^2 * ángulo) / 360
            angulo  = Integer.parseInt(txt_13.getText());
            radioMa = Integer.parseInt(txt_7.getText());
            resultado = (3.14159 * ((radioMa*radioMa) * angulo)) / 360;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_9ActionPerformed

    private void b_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_10ActionPerformed
          if (txt_1.getText().length() == 0 | txt_2.getText().length() == 0 | txt_3.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            lado  = Integer.parseInt(txt_1.getText());
            base = Integer.parseInt(txt_2.getText());
            altura = Integer.parseInt(txt_3.getText());
            resultado = (altura * lado * base);
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_10ActionPerformed

    private void b_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_11ActionPerformed
      if (txt_1.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            lado  = Integer.parseInt(txt_1.getText());
            resultado = lado * lado * lado;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_11ActionPerformed

    private void b_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_12ActionPerformed
        // V = (4 * Pi * radio^3) / 3
              if (txt_14.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            radioMa  = Integer.parseInt(txt_14.getText());
            resultado = (4 * 3.14159 * (radioMa * radioMa * radioMa))/3;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_12ActionPerformed

    private void b_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_13ActionPerformed
     // Pi * radio^2 * altura
            if (txt_14.getText().length() == 0 | txt_3.getText().length() == 0 ) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            altura  = Integer.parseInt(txt_3.getText());
            radioMa = Integer.parseInt(txt_14.getText());
            resultado = (3.14159 * ((radioMa*radioMa) *altura ));
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_13ActionPerformed

    private void b_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_14ActionPerformed
        // V = (3.14159 * area^2 * altura) / 3 
        if (txt_1.getText().length() == 0 | txt_2.getText().length() == 0 | txt_3.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor");
        } else {
            lado  = Integer.parseInt(txt_1.getText());
            base = Integer.parseInt(txt_2.getText());
            altura = Integer.parseInt(txt_3.getText());
            resultado = (3.14159 * ((lado * base) * (lado * base))* altura) / 3;
            Resultado.setText("R: " +resultado);
           borr();
        }
    }//GEN-LAST:event_b_14ActionPerformed

    private void b_cerr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerr2ActionPerformed
        jj1.setVisible(false);
    }//GEN-LAST:event_b_cerr2ActionPerformed

    private void b_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_piActionPerformed
    try{
        File path = new File("Matematicas/pi.pdf");
        Desktop.getDesktop().open(path);
    }catch(IOException ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_b_piActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     jj1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     try{
        File path = new File("Problemas_Ecuaciones_Secundaria.html");
        Desktop.getDesktop().open(path);
    }catch(IOException ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
      jButton1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
      jButton1.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
       jButton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
      jButton2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
       jButton3.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
      jButton5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
     jButton2.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
      jButton3.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
      jButton5.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      try{
        File path = new File("Matematicas/Razon_Ma.pdf");
        Desktop.getDesktop().open(path);
    }catch(IOException ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
        File path = new File("Matematicas/Razon_Ma2.pdf");
        Desktop.getDesktop().open(path);
    }catch(IOException ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
        File path = new File("Matematicas/Razon_Ma3.pdf");
        Desktop.getDesktop().open(path);
    }catch(IOException ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matematicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matematicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_1;
    private javax.swing.JButton A_10;
    private javax.swing.JButton A_11;
    private javax.swing.JButton A_12;
    private javax.swing.JButton A_13;
    private javax.swing.JButton A_14;
    private javax.swing.JButton A_2;
    private javax.swing.JButton A_3;
    private javax.swing.JButton A_4;
    private javax.swing.JButton A_5;
    private javax.swing.JButton A_6;
    private javax.swing.JButton A_7;
    private javax.swing.JButton A_8;
    private javax.swing.JButton A_9;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton b_1;
    private javax.swing.JButton b_10;
    private javax.swing.JButton b_11;
    private javax.swing.JButton b_12;
    private javax.swing.JButton b_13;
    private javax.swing.JButton b_14;
    private javax.swing.JButton b_15;
    private javax.swing.JButton b_16;
    private javax.swing.JButton b_2;
    private javax.swing.JButton b_3;
    private javax.swing.JButton b_4;
    private javax.swing.JButton b_5;
    private javax.swing.JButton b_6;
    private javax.swing.JButton b_7;
    private javax.swing.JButton b_8;
    private javax.swing.JButton b_9;
    private javax.swing.JButton b_cerr;
    private javax.swing.JButton b_cerr2;
    private javax.swing.JButton b_min;
    private javax.swing.JButton b_pi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JInternalFrame jj1;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_10;
    private javax.swing.JLabel lb_11;
    private javax.swing.JLabel lb_12;
    private javax.swing.JLabel lb_13;
    private javax.swing.JLabel lb_14;
    private javax.swing.JLabel lb_2;
    private javax.swing.JLabel lb_3;
    private javax.swing.JLabel lb_4;
    private javax.swing.JLabel lb_5;
    private javax.swing.JLabel lb_6;
    private javax.swing.JLabel lb_7;
    private javax.swing.JLabel lb_8;
    private javax.swing.JLabel lb_9;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_10;
    private javax.swing.JTextField txt_11;
    private javax.swing.JTextField txt_12;
    private javax.swing.JTextField txt_13;
    private javax.swing.JTextField txt_14;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_6;
    private javax.swing.JTextField txt_7;
    private javax.swing.JTextField txt_8;
    private javax.swing.JTextField txt_9;
    // End of variables declaration//GEN-END:variables
}
