/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        botonTrans();
        
        this.setLocationRelativeTo(null);
        
    }
    Login L = new Login();
    
    public void botonTrans(){
        b_cerr.setOpaque(false);
        b_cerr.setBorderPainted(false);
        b_cerr.setContentAreaFilled(false);
        b_mini.setOpaque(false);
        b_mini.setBorderPainted(false);
        b_mini.setContentAreaFilled(false);
        primer.setOpaque(false);
        primer.setBorderPainted(false);
        primer.setContentAreaFilled(false);
        segun.setOpaque(false);
        segun.setBorderPainted(false);
        segun.setContentAreaFilled(false);
        tercer.setOpaque(false);
        tercer.setBorderPainted(false);
        tercer.setContentAreaFilled(false);
        leer.setOpaque(false);
        leer.setBorderPainted(false);
        leer.setContentAreaFilled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_mini = new javax.swing.JButton();
        b_cerr = new javax.swing.JButton();
        tercer = new javax.swing.JButton();
        primer = new javax.swing.JButton();
        segun = new javax.swing.JButton();
        leer = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        b_mini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_miniActionPerformed(evt);
            }
        });
        getContentPane().add(b_mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 40, 40));

        b_cerr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        b_cerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerrActionPerformed(evt);
            }
        });
        getContentPane().add(b_cerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, 40));

        tercer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/tercero.png"))); // NOI18N
        tercer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercerActionPerformed(evt);
            }
        });
        getContentPane().add(tercer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 110, 130));

        primer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/premio.png"))); // NOI18N
        primer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerActionPerformed(evt);
            }
        });
        getContentPane().add(primer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 110, 130));

        segun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/segundo.png"))); // NOI18N
        segun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segunActionPerformed(evt);
            }
        });
        getContentPane().add(segun, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 110, 130));

        leer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerebro.png"))); // NOI18N
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });
        getContentPane().add(leer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 70, 60));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/madera.jpg"))); // NOI18N
        fondo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 820, 320));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde_fondo.jpg"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void b_miniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_miniActionPerformed
        setExtendedState(Menu.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_b_miniActionPerformed

    private void b_cerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerrActionPerformed
      System.exit(0);
    }//GEN-LAST:event_b_cerrActionPerformed

    private void primerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerActionPerformed
        PrimerAnio PA = new PrimerAnio();
        PA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_primerActionPerformed

    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed
       Lecturas Leer = new Lecturas();
       Leer.setVisible(true);
       this.setVisible(false);
       L.setVisible(false);
       L.setVisible(false);
    }//GEN-LAST:event_leerActionPerformed

    private void segunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segunActionPerformed
       SegundoAnio SA = new SegundoAnio();
       SA.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_segunActionPerformed

    private void tercerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercerActionPerformed
        TercerAnio TA = new TercerAnio();
        TA.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tercerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cerr;
    private javax.swing.JButton b_mini;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton leer;
    private javax.swing.JButton primer;
    private javax.swing.JButton segun;
    private javax.swing.JButton tercer;
    // End of variables declaration//GEN-END:variables
}
