/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author USER
 */
public class Olvido extends javax.swing.JFrame {
private static Scanner sc;
private static int intentos;
private static String user, pwd, email;
    /**
     * Creates new form Olvido
     */
    public Olvido() {
        initComponents();
        botonTrans();
        this.setLocationRelativeTo(null);
    }
    
    public void botonTrans(){
        MinOlvi.setOpaque(false);
        MinOlvi.setContentAreaFilled(false);
        MinOlvi.setBorderPainted(false);
        SaliOlvi.setOpaque(false);
        SaliOlvi.setBorderPainted(false);
        SaliOlvi.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuOlvi = new javax.swing.JTextField();
        txt_correoOlvi = new javax.swing.JTextField();
        MostrarOlviPwd = new javax.swing.JButton();
        MinOlvi = new javax.swing.JButton();
        SaliOlvi = new javax.swing.JButton();
        lbl_olviPwd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuOlvi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuOlviKeyTyped(evt);
            }
        });
        getContentPane().add(txt_usuOlvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 180, 30));

        txt_correoOlvi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_correoOlviKeyTyped(evt);
            }
        });
        getContentPane().add(txt_correoOlvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 180, 30));

        MostrarOlviPwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MostrarOlviPwd.setText("Mostrar Contraseña");
        MostrarOlviPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarOlviPwdActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarOlviPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, 40));

        MinOlvi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        MinOlvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinOlviActionPerformed(evt);
            }
        });
        getContentPane().add(MinOlvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 40, 40));

        SaliOlvi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        SaliOlvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaliOlviActionPerformed(evt);
            }
        });
        getContentPane().add(SaliOlvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 10, 40, 40));

        lbl_olviPwd.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        lbl_olviPwd.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_olviPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/precaucion (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 130, 130));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numbre del usuario: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 100, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/adve2.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jLabel5.setName(""); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaliOlviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaliOlviActionPerformed
        Login L = new Login();
        this.setVisible(false);
        L.setVisible(true);
    }//GEN-LAST:event_SaliOlviActionPerformed

    private void MinOlviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinOlviActionPerformed
        setExtendedState(Olvido.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_MinOlviActionPerformed

    private void MostrarOlviPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarOlviPwdActionPerformed
        
        FileReader fr = null;
        try {
        
        int NLinea = 0;
        int i =0;
        String[] usuarios = null;
        String linea;
        sc = new Scanner(new File("Datos.txt"));
        File  f = new File("Datos.txt");
        fr =  new FileReader(f);
        BufferedReader br = new  BufferedReader(fr);
            try {
                while((linea = br.readLine()) != null){
                    NLinea ++;
                }  
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        usuarios = new String[NLinea];
        while(sc.hasNextLine()){
            usuarios[i++] = sc.nextLine();
        }
        intentos ++;
        email = txt_correoOlvi.getText();
        user =  txt_usuOlvi.getText();
        Seguridad s = new Seguridad();
        s.RecuperarUsuario(usuarios, email, user, pwd, intentos);
        lbl_olviPwd.setText(pwd);
        txt_usuOlvi.setText("");
        txt_correoOlvi.setText("");
       

    } catch (FileNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

    }
        
       // lbl_olviPwd.setText("10Yony10");
    }//GEN-LAST:event_MostrarOlviPwdActionPerformed

    private void txt_usuOlviKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuOlviKeyTyped
                char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_usuOlviKeyTyped

    private void txt_correoOlviKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoOlviKeyTyped
               char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_correoOlviKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Olvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Olvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Olvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Olvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Olvido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MinOlvi;
    private javax.swing.JButton MostrarOlviPwd;
    private javax.swing.JButton SaliOlvi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_olviPwd;
    private javax.swing.JTextField txt_correoOlvi;
    private javax.swing.JTextField txt_usuOlvi;
    // End of variables declaration//GEN-END:variables
}
