/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author USER
 */
public class PrimerAnio extends javax.swing.JFrame {

    /**
     * Creates new form PrimerAnio
     */
    public PrimerAnio() {
        initComponents();
        this.setLocationRelativeTo(null);
        botonTrans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void botonTrans(){
        salir.setOpaque(false);
        salir.setContentAreaFilled(false);
        salir.setBorderPainted(false);
        min.setOpaque(false);
        min.setContentAreaFilled(false);
        min.setBorderPainted(false);
        Geogra.setContentAreaFilled(false);
        Geogra.setBorderPainted(false);
        Geogra.setOpaque(false);
        Ingles.setOpaque(false);
        Ingles.setContentAreaFilled(false);
        Ingles.setBorderPainted(false);
        Mate.setOpaque(false);
        Mate.setContentAreaFilled(false);
        Mate.setBorderPainted(false);
        Español.setBorderPainted(false);
        Español.setOpaque(false);
        Español.setContentAreaFilled(false);
        etica.setContentAreaFilled(false);
        etica.setBorderPainted(false);
        etica.setOpaque(false);
        Biolo.setContentAreaFilled(false);
        Biolo.setBorderPainted(false);
        Biolo.setOpaque(false);
        Histo.setOpaque(false);
        Histo.setContentAreaFilled(false);
        Histo.setBorderPainted(false);
        notas.setContentAreaFilled(false);
        notas.setBorderPainted(false);
        notas.setOpaque(false);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        min = new javax.swing.JButton();
        Mate = new javax.swing.JButton();
        Ingles = new javax.swing.JButton();
        Geogra = new javax.swing.JButton();
        Español = new javax.swing.JButton();
        Biolo = new javax.swing.JButton();
        Histo = new javax.swing.JButton();
        etica = new javax.swing.JButton();
        notas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 40, 40));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, 40));

        Mate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/matematicas.png"))); // NOI18N
        Mate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateActionPerformed(evt);
            }
        });
        getContentPane().add(Mate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 140, 140));

        Ingles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inglaterra.png"))); // NOI18N
        Ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InglesActionPerformed(evt);
            }
        });
        getContentPane().add(Ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 140, 120));

        Geogra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historia.png"))); // NOI18N
        Geogra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeograActionPerformed(evt);
            }
        });
        getContentPane().add(Geogra, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 120, 130));

        Español.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/estudiar.png"))); // NOI18N
        Español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspañolActionPerformed(evt);
            }
        });
        getContentPane().add(Español, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 140, 140));

        Biolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/adn.png"))); // NOI18N
        Biolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BioloActionPerformed(evt);
            }
        });
        getContentPane().add(Biolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 130, 130));

        Histo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historia (1).png"))); // NOI18N
        Histo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoActionPerformed(evt);
            }
        });
        getContentPane().add(Histo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 140, -1));

        etica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/etica.png"))); // NOI18N
        etica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eticaActionPerformed(evt);
            }
        });
        getContentPane().add(etica, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 120, 120));

        notas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lista.png"))); // NOI18N
        getContentPane().add(notas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 130, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Notas diarias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Formación Cívica y Ética");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Ingles");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Historia Universal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Español");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Geografia");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Matemáticas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Biologia");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f_verde.png"))); // NOI18N
        fondo.setText(" ");
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Menu M = new Menu();
        M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void InglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InglesActionPerformed
        Ingles I = new Ingles();
        I.setVisible(true);
       
        
    }//GEN-LAST:event_InglesActionPerformed

    private void BioloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BioloActionPerformed
       Biologia B = new Biologia();
       B.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_BioloActionPerformed

    private void HistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoActionPerformed
     HistoriaUniversal HU = new HistoriaUniversal();
     HU.setVisible(true);
    
    }//GEN-LAST:event_HistoActionPerformed

    private void GeograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeograActionPerformed
      Geografia Geo = new Geografia();
          Geo.setVisible(true);
          this.setVisible(false);
      
    }//GEN-LAST:event_GeograActionPerformed

    private void MateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateActionPerformed
     Matematicas Ma = new Matematicas();
        Ma.setVisible(true);
    }//GEN-LAST:event_MateActionPerformed

    private void EspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspañolActionPerformed
     Español E = new Español();
     E.setVisible(true);
    }//GEN-LAST:event_EspañolActionPerformed

    private void eticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eticaActionPerformed
      Formacion Fr = new Formacion();
     Fr.setVisible(false);
    }//GEN-LAST:event_eticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimerAnio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Biolo;
    private javax.swing.JButton Español;
    private javax.swing.JButton Geogra;
    private javax.swing.JButton Histo;
    private javax.swing.JButton Ingles;
    private javax.swing.JButton Mate;
    private javax.swing.JButton etica;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton min;
    private javax.swing.JButton notas;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
