
package Formularios;

//import Clases.Registro_csv;
//import com.oracle.csvreader.CsvWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Registrarse extends javax.swing.JFrame {
    DefaultListModel ModeloLista;
    Seguridad S = new Seguridad();
    
    
    public Registrarse() {
        initComponents();
        botonTrasparente();
        this.setLocationRelativeTo(null);
        ModeloLista = new DefaultListModel();
    }
    
    public void botonTrasparente(){
        B_CerR.setContentAreaFilled(false);
        B_CerR.setOpaque(false);
        B_CerR.setBorderPainted(false);
        B_MinR.setOpaque(false);
        B_MinR.setBorderPainted(false);
        B_MinR.setContentAreaFilled(false);
        info.setBorderPainted(false);
        info.setContentAreaFilled(false);
        info.setOpaque(false);
    }
   // public static void ExportarCSV(List<Registro_csv> Regi){
//      String salidaArchivo = "Registro.txt";  
//      boolean existe = new File(salidaArchivo).exists();
//      //si existe un archivo llamado asi lo borra
//      if(existe){
//          File archivoUsua = new File(salidaArchivo);
//          archivoUsua.delete();
//      }
//      //crea el archivo
//          try{
//              
//              CsvWriter salidaCSV = new CsvWriter(new FileWriter(salidaArchivo, true), ',');
//              //Datos para identificar la columna
//              salidaCSV.write("Nombre");
//              salidaCSV.write("Correo");
//              salidaCSV.write("Pwd");
//              salidaCSV.endRecord(); //Para dejar de escribir en el archivo
//              //Para recorrer la lista y lo incerte en el archivo.
//              for(Registro_csv Regis : Regi){
//                  salidaCSV.write(Regis.getNombre());
//                  salidaCSV.write(Regis.getCorreo());
//                  salidaCSV.write(Regis.getPwd());
//                  salidaCSV.endRecord();
//              }
//          }catch(IOException e){
//              e.printStackTrace();
//          }
   // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        txt_usuR = new javax.swing.JTextField();
        txt_pwdR = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        H = new javax.swing.JRadioButton();
        M = new javax.swing.JRadioButton();
        B_guardarR = new javax.swing.JButton();
        info = new javax.swing.JButton();
        B_MinR = new javax.swing.JButton();
        B_CerR = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuR.setBackground(new java.awt.Color(176, 111, 83));
        txt_usuR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_usuR.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuR.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txt_usuR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuRKeyTyped(evt);
            }
        });
        getContentPane().add(txt_usuR, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 200, 30));

        txt_pwdR.setBackground(new java.awt.Color(167, 106, 78));
        txt_pwdR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_pwdR.setForeground(new java.awt.Color(255, 255, 255));
        txt_pwdR.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txt_pwdR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pwdRKeyTyped(evt);
            }
        });
        getContentPane().add(txt_pwdR, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 200, 30));

        txt_correo.setBackground(new java.awt.Color(176, 111, 83));
        txt_correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_correo.setForeground(new java.awt.Color(255, 255, 255));
        txt_correo.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_correoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 200, 30));

        sexo.add(H);
        H.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 20, -1));

        sexo.add(M);
        M.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 20, -1));

        B_guardarR.setBackground(new java.awt.Color(0, 153, 0));
        B_guardarR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_guardarR.setForeground(new java.awt.Color(255, 255, 255));
        B_guardarR.setText("Registrar");
        B_guardarR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        B_guardarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_guardarRActionPerformed(evt);
            }
        });
        getContentPane().add(B_guardarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 140, 30));

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/informacion (2).png"))); // NOI18N
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        getContentPane().add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 30, 30));

        B_MinR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        B_MinR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MinRActionPerformed(evt);
            }
        });
        getContentPane().add(B_MinR, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 40, -1));

        B_CerR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        B_CerR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CerRActionPerformed(evt);
            }
        });
        getContentPane().add(B_CerR, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 40, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/grupo-de-usuario (1).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 70, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Correo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/empresario.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mujer-de-negocios.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TTT.png"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 230, 220));

        fondo1.setBackground(new java.awt.Color(255, 255, 255));
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blan.png"))); // NOI18N
        fondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 310, 370));

        fondo2.setBackground(new java.awt.Color(0, 0, 153));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris.png"))); // NOI18N
        fondo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 490, 370));

        Fondo.setBackground(new java.awt.Color(113, 76, 58));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/106.jpg"))); // NOI18N
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CerRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CerRActionPerformed
              Login L = new Login();
        this.setVisible(false);
        L.setVisible(true);
    }//GEN-LAST:event_B_CerRActionPerformed

    private void B_MinRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MinRActionPerformed
      setExtendedState(Registrarse.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_B_MinRActionPerformed

    private void B_guardarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_guardarRActionPerformed

         if (txt_correo.getText().length() == 0 || txt_usuR.getText().length() == 0 || txt_pwdR.getText().length() == 0 || 
                 !txt_correo.getText().contains("@") || !txt_correo.getText().contains(".") ) {
            JOptionPane.showMessageDialog(null, "Verifique que su correo sea valido");
        } else {
     String email = (txt_correo.getText());
     String usu = (txt_usuR.getText());
     String pwd = (txt_pwdR.getText());
     
      S.Registrar(txt_correo.getText(), txt_usuR.getText(), txt_pwdR.getText() );
      JOptionPane.showMessageDialog(null, "Usuario Agregado Correctamente");
      ModeloLista.addElement(email);
      ModeloLista.addElement(usu);
      ModeloLista.addElement(pwd);
      
         }
        Login L = new Login();
        this.setVisible(false);
        L.setVisible(true);
    }//GEN-LAST:event_B_guardarRActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        JOptionPane.showMessageDialog(rootPane,"El correo sirve para recuper la contraseña en caso de un olvido.");
    }//GEN-LAST:event_infoActionPerformed

    private void txt_usuRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuRKeyTyped
              char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_usuRKeyTyped

    private void txt_pwdRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwdRKeyTyped
                char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_pwdRKeyTyped

    private void txt_correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyTyped
               char c = evt.getKeyChar();
        if (c == ' ') {
            evt.consume();
//            char v = evt.getKeyChar();
//            if(v != '@'){
//                evt.consume();
//            }
            
        }
    }//GEN-LAST:event_txt_correoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_CerR;
    private javax.swing.JButton B_MinR;
    private javax.swing.JButton B_guardarR;
    private javax.swing.JLabel Fondo;
    private javax.swing.JRadioButton H;
    private javax.swing.JRadioButton M;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_pwdR;
    private javax.swing.JTextField txt_usuR;
    // End of variables declaration//GEN-END:variables
}
