/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author USER
 */
public class SegundoAnio extends javax.swing.JFrame {

    /**
     * Creates new form SegundoAnio
     */
    public SegundoAnio() {
        initComponents();
        this.setLocationRelativeTo(null);
        buton_trans();
    }
    
    public void buton_trans(){
        b_Espa.setOpaque(false);
        b_Espa.setContentAreaFilled(false);
        b_Espa.setBorderPainted(false);
        b_Fisi.setOpaque(false);
        b_Fisi.setContentAreaFilled(false);
        b_Fisi.setBorderPainted(false);
        b_Formacion.setOpaque(false);
        b_Formacion.setContentAreaFilled(false);
        b_Formacion.setBorderPainted(false);
        b_Histo.setOpaque(false);
        b_Histo.setContentAreaFilled(false);
        b_Histo.setBorderPainted(false);
        b_Ingles.setOpaque(false);
        b_Ingles.setContentAreaFilled(false);
        b_Ingles.setBorderPainted(false);
        b_Mate.setOpaque(false);
        b_Mate.setContentAreaFilled(false);
        b_Mate.setBorderPainted(false);
        b_diario.setOpaque(false);
        b_diario.setContentAreaFilled(false);
        b_diario.setBorderPainted(false);
        b_cerr.setOpaque(false);
        b_cerr.setContentAreaFilled(false);
        b_cerr.setBorderPainted(false);
        b_min.setOpaque(false);
        b_min.setContentAreaFilled(false);
        b_min.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_cerr = new javax.swing.JButton();
        b_min = new javax.swing.JButton();
        b_diario = new javax.swing.JButton();
        b_Espa = new javax.swing.JButton();
        b_Mate = new javax.swing.JButton();
        b_Fisi = new javax.swing.JButton();
        b_Ingles = new javax.swing.JButton();
        b_Formacion = new javax.swing.JButton();
        b_Histo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_cerr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar (2).png"))); // NOI18N
        b_cerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerrActionPerformed(evt);
            }
        });
        getContentPane().add(b_cerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 40, -1));

        b_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/minimizar.png"))); // NOI18N
        b_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_minActionPerformed(evt);
            }
        });
        getContentPane().add(b_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, -1));

        b_diario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lista.png"))); // NOI18N
        getContentPane().add(b_diario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        b_Espa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/estudiar.png"))); // NOI18N
        b_Espa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EspaActionPerformed(evt);
            }
        });
        getContentPane().add(b_Espa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        b_Mate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/matematicas.png"))); // NOI18N
        b_Mate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_MateActionPerformed(evt);
            }
        });
        getContentPane().add(b_Mate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        b_Fisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/asistencia-sanitaria-y-medica.png"))); // NOI18N
        b_Fisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_FisiActionPerformed(evt);
            }
        });
        getContentPane().add(b_Fisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        b_Ingles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inglaterra.png"))); // NOI18N
        b_Ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_InglesActionPerformed(evt);
            }
        });
        getContentPane().add(b_Ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        b_Formacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/etica.png"))); // NOI18N
        b_Formacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_FormacionActionPerformed(evt);
            }
        });
        getContentPane().add(b_Formacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        b_Histo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historia (1).png"))); // NOI18N
        b_Histo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_HistoActionPerformed(evt);
            }
        });
        getContentPane().add(b_Histo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Notas Diarias");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Español");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Formación Civica y Etica");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText(" Matemátias");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("Física");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("Historia Universal");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 120, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setText("Ingles");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/V_ver.png"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_cerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerrActionPerformed
       Menu M = new Menu();
       M.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_cerrActionPerformed

    private void b_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_minActionPerformed
       setExtendedState(SegundoAnio.CROSSHAIR_CURSOR);
    }//GEN-LAST:event_b_minActionPerformed

    private void b_InglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_InglesActionPerformed
        Ingles I = new Ingles();
        I.setVisible(true);
        
    }//GEN-LAST:event_b_InglesActionPerformed

    private void b_FisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_FisiActionPerformed
      this.setVisible(false);
      Fisica F = new Fisica();
      F.setVisible(true);
    }//GEN-LAST:event_b_FisiActionPerformed

    private void b_HistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_HistoActionPerformed
     
      HistoriaUniversal  HU= new HistoriaUniversal();
      HU.setVisible(true);
    }//GEN-LAST:event_b_HistoActionPerformed

    private void b_MateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_MateActionPerformed
          Matematicas Ma = new Matematicas();
        Ma.setVisible(true);
    }//GEN-LAST:event_b_MateActionPerformed

    private void b_EspaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_EspaActionPerformed
      Español E = new Español();
     E.setVisible(true);
    }//GEN-LAST:event_b_EspaActionPerformed

    private void b_FormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_FormacionActionPerformed
      Formacion Fr = new Formacion();
     Fr.setVisible(false);
    }//GEN-LAST:event_b_FormacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundoAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundoAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundoAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundoAnio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundoAnio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Espa;
    private javax.swing.JButton b_Fisi;
    private javax.swing.JButton b_Formacion;
    private javax.swing.JButton b_Histo;
    private javax.swing.JButton b_Ingles;
    private javax.swing.JButton b_Mate;
    private javax.swing.JButton b_cerr;
    private javax.swing.JButton b_diario;
    private javax.swing.JButton b_min;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
